# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-AWS-EB
env:
  EB_PACKAGE_S3_BUCKET_NAME : "color-app-packages-bucket"
  EB_APPLICATION_NAME       : "flask-app"
  EB_ENVIRONMENT_NAME       : "Flaskapp-env"
  DEPLOY_PACKAGE_NAME       : "flask-app${{ github.sha}}.zip"
  AWS_REGION_NAME           : "eu-central-1"
     

# Controls when the workflow will run
on:
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 ci_part: 
  runs-on: ubuntu-latest
    
  steps:
  - name: Git clone our repo
    uses: actions/checkout@v2
      
  - name: Create ZIP deployment package
    run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region            : ${{ env.AWS_REGION_NAME }}
      
      
  - name: Copy Deployment package to S3 bucket
    run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
    
  - name: CI part Finish
    run: echo "CI pipeline finished"
      
     
    
        
       
