# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-AWS-EB
env:
  EB_PACKAGE_S3_BUCKET_NAME : "color-app-packages-bucket"
  EB_APPLICATION_NAME       : "flask-app"
  EB_ENVIRONMENT_NAME       : "Flaskapp-env"
  DEPLOY_PACKAGE_NAME       : "flask-app${{ github.sha}}.zip"
  AWS_REGION_NAME           : "eu-central-1"
     

# Controls when the workflow will run
on:
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 ci_part: 
  runs-on: ubuntu-latest
    
  steps:
  - name: Git clone our repo
    uses: actions/checkout@v2
      
  - name: Create ZIP deployment package
    run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
       
